### ISSUE TITLE
[New Workshop] CITEViz

### ISSUE THREAD

**Issue by gartician** [seandavi/orchestra-contributions#10]
Please supply the following information:

Short title: eg., CITEViz: Replicating the Interactive Flow Cytometry Workflow in CITE-Seq
Workshop URL: eg., https://github.com/gartician/CITEVizWorkshop
Workshop docker image: ghcr.io/gartician/citevizworkshop
Workshop port: 8787
Workshop memory request: 4GB
Workshop description: 

Multi-omic single-cell sequencing assays measure multiple macromolecules in the same cell and can often yield new insights not revealed with a single modality. For example, CITE-Seq (Cellular Indexing of Transcriptomes and Epitopes by Sequencing) simultaneously profiles the single-cell RNA transcriptome and the surface protein expression. The extra dimensions of data in these assays can be leveraged to better identify cell clusters - an essential step for downstream analyses and interpretation. To facilitate cell cluster classification and visualization in CITE-Seq, we developed CITE-Viz.

CITE-Viz is a single-cell visualization platform with a custom module that replicates the interactive flow-cytometry gating workflow. With CITE-Viz, users can investigate CITE-Seq specific quality control (QC) metrics, view multi-omic co-expression feature plots, and classify cell clusters by iteratively gating on the abundance of cell surface markers.

CITE-Viz was developed to make multi-modal single-cell analysis accessible to a wide variety of biologists, with the aim to discover new insights into their data and to facilitate novel hypothesis generation. In this workshop, we will go over all the features of CITEViz. 

Add any additional notes below.

I want to add a fairly large Seurat object into this R-Shiny demo (125 MB). It is located here `inst/extdata/small_pbmc_2.rds`, but every time I push the "upload" button the file explorer defaults to the local computer's file system instead of what's inside the container. Is it okay if I pre-download the Seurat object to a local computer before/during my workshop? Otherwise everything seems fine.

**Comment by gartician** [comment]
I can also shorten my workshop description if it's too verbose.

**Comment by seandavi** [comment]
If the data are in `inst/extdata/small_pbmc_2.Rds` you should be able to just have participants use loadRDS. No need to upload since the file is already in the image. I may be misunderstanding what is going on, though.

**Comment by seandavi** [comment]
Should be on Orchestra now. Thanks for the contribution.
