### ISSUE TITLE
SpatialFeatureExperiment workshop

### ISSUE THREAD

**Issue by lambdamoses** [seandavi/orchestra-contributions#11]
Please supply the following information:

Short title: SpatialFeatureExperiment Bioc2022
Workshop URL: https://github.com/lambdamoses/SFEWorkshop
Workshop docker image: ghcr.io/lambdamoses/sfeworkshop
Workshop port: 8787
Workshop memory request: 4GB
Workshop description: In this workshop, we demonstrate the new `SpatialFeatureExperiment` S4 class that integrates `SpatialExperiment` with `sf` Simple Features to bring geospatial tools to spatial transcriptomics. First, we present the structure and interactions with the SFE class. Next, we present the `Voyager` package for exploratory spatial data analyses with the SFE class.

I'm demonstrating parallel processing. At most 2 cores are used. Is it possible to request 2 CPU cores?

**Comment by seandavi** [comment]
The machines that Orchestra uses are not large (just meant for demonstration purposes), but you should still be able to demonstrate parallel processing.

**Comment by seandavi** [comment]
Should be added now. Thanks for the contribution.
