### ISSUE TITLE
[New Workshop]TrendCatcherWorkshopBIOC2022

### ISSUE THREAD

**Issue by jaleesr** [seandavi/orchestra-contributions#12]
Please supply the following information:

Short title: TrendCatcher, a versatile R package for identifying dynamic differentially expressed genes (DDEGs) in RNA-seq longitudinal studies.
Workshop URL: https://github.com/jaleesr/TrendCatcherWorkshopBIOC2022
Workshop docker image: ghcr.io/jaleesr/trendcatcherworkshopbioc2022
Workshop port: 8787 for Rstudio-based workshops
Workshop memory request: 16GB
Workshop description: TrendCatcher is a versatile R package for identifying dynamic differentially expressed genes (DDEGs) in RNA-seq longitudinal studies. A time course experiment is a widely used design in the study of cellular processes such as cell differentiation or response to external stimuli. Temporal changes to the gene expression, such as mRNA, is the key to characterizing such biological processes. Here, we present a versatile R package named TrendCatcher to identify the dynamic differentially expressed genes along the biological process time course. We will show 4 vignettes of how to use TrendCatcher to analyze your own time course RNA-seq dataset.

Workshop goals,
1. Learn how to run TrendCatcher main functions.
2. Learn the workflow of using TrendCatcher to analyze time course RNA-seq datasets.
3. Understand how to interpret the output of TrendCatcher.
4. Know how to visualize results.

**Comment by seandavi** [comment]
Should be in. Thanks for the contribution.
