### ISSUE TITLE
Accessing Human Cell Atlas Data Locally And On The Anvil Cloud

### ISSUE THREAD

**Issue by mtmorgan** [seandavi/orchestra-contributions#13]
Please supply the following information:

Short title: Accessing Human Cell Atlas Data Locally And On The Anvil Cloud
Workshop URL: https://github.com/mtmorgan/ExploringHCACxG
Workshop docker image: ghcr.io/mtmorgan/exploringhcacxg:latest
Workshop port: 8787
Workshop memory request: 4GB
Workshop description: This short workshop demonstrates how three R/Bioconductor packages provide access to the increasing number of single cell gene expression data sets produced as part of the Human Cell Atlas. The cellxgenedp package (https://bioconductor.org/packages/cellxgenedp) allows discovery, download for import into R / Bioconductor as SingleCellExperiment objects, and visual exploration through the cellxgene data portal of more than 300 consistently-processed datasets. The hca package (https://bioconductor.org/packages/hca) provides additional, fine-grained, access to 208 projects, including 50 that have been processed by standard Human Cell Atlas workflows defined in WDL (Workflow Description Language). Description of the processing workflow in WDL means that other datasets, including those produced by individual labs, can be consistently processed from fastq or bam files to objects that are easily integrated into R / Bioconductor work flows. This process is particularly easy when performed in the AnVIL computational cloud, a process facilitated by the AnVIL (https://bioconductor.org/packages/AnVIL) package.

Add any additional notes below.

**Comment by seandavi** [comment]
Should be in. Sorry for the delay.
