### ISSUE TITLE
[New Workshop]: GenomicDistributions

### ISSUE THREAD

**Issue by kkupkova** [seandavi/orchestra-contributions#14]
Please supply the following information:

Short title: GenomicDistributions demo - BioC2022
Workshop URL: https://github.com/kkupkova/GenomicDistributionsBioC2022
Workshop docker image: ghcr.io/kkupkova/genomicdistributionsbioc2022:latest
Workshop port: 8787
Workshop memory request: 3GB
Workshop description: During this workshop participants will be introduced to GenomicDistributions package. At first, we will go over a general introduction to GenomicDistributions, where we will learn about the purpose, design, and advantages of GenomicDistributions. Followed by instructor-led demo, we will go through all of the functions included in GenomicDistributions, where participants will be able to try the functions on provided example datasets. The participants will learn, how to calculate and plot summary statistics extracted from the example datasets and how to further customize plots generated with GenomicDistributions. Some of the GenomicDistributions functions require genome annotations (for hg19, hg38, and mm10 these are all included in the GenomicDistributionsData package and passed to a subset of functions ending with the suffix “Ref”), the participants will be taught how to easily create and use these annotations. At the end of the workshop, all participants will be able to extract following summary statistics about their regions of interest: distribution over chromosomes, distances from genomic features (e.g., TSSs), distribution over annotation classes, signal summary in regions, region widths, distances to the nearest neighbor, GC content, and dinucleotide frequencies.

Add any additional notes below.

**Comment by seandavi** [comment]
Should be available now, @kkupkova. Thanks for the contribution.
