### ISSUE TITLE
nullranges

### ISSUE THREAD

**Issue by EricSDavis** [seandavi/orchestra-contributions#15]
Please supply the following information:

Short title: nullranges: Generation of nullranges via bootstrapping or covariate matching
Workshop URL: https://github.com/EricSDavis/Bioc2022nullranges
Workshop docker image: eg., ghci.io/EricSDavis/Bioc2022nullranges
Workshop port: eg., 8787 for Rstudio-based workshops
Workshop memory request: eg., 2GB
Workshop description: In this workshop, we will show how to use `nullranges` for generating sets of null hypothesis genomic ranges. You will learn about the two approaches for generating null feature sets: covariate-matched subsampling with `matchRanges` and bootstrapping ranges with `bootRanges`. Finally, you will see how `nullranges` integrates with existing Bioconductor packages as it is applied to biological examples.

**Comment by EricSDavis** [comment]
Please bump up the requested memory from 2GB to 4GB.

**Comment by seandavi** [comment]
Should be in Orchestra. Thanks for the contribution.
