### ISSUE TITLE
How to update workshop

### ISSUE THREAD

**Issue by jmacdon** [seandavi/orchestra-contributions#16]
Hi Sean,

My workshop depends on an AnnotationHub object that isn't downloading, so I changed to something that will download. It is apparently building the HTML vignette now (https://github.com/jmacdon/Bioc2022Anno/runs/7528389476?check_suite_focus=true), but I don't see the HTML vignette on orchestra, nor if I get the updated docker container. Is there something additional I need to do to push the updated package?

Thanks,

Jim

**Comment by seandavi** [comment]
Orchestra will pull the latest image, so if you update the docker, things should be good. Once the build is done, give it a try. If you still have problems, follow up and I'll  look into it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: James W. MacDonald ***@***.***>
Sent: Tuesday, July 26, 2022 6:35:20 PM
To: seandavi/orchestra-contributions ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [seandavi/orchestra-contributions] How to update workshop (Issue #16)


Hi Sean,

My workshop depends on an AnnotationHub object that isn't downloading, so I changed to something that will download. It is apparently building the HTML vignette now (https://github.com/jmacdon/Bioc2022Anno/runs/7528389476?check_suite_focus=true), but I don't see the HTML vignette on orchestra, nor if I get the updated docker container. Is there something additional I need to do to push the updated package?

Thanks,

Jim

**Comment by jmacdon** [comment]
That's the thing. I've updated GitHub and the actions seem to go OK, but neither the docker nor the orchestra site seem to have the HTML version of the vignette.

**Comment by gartician** [comment]
I also got a PR accepted (CITEViz #10, Friday 15:30) and I'm not seeing an HTML vignette on my package demo in this [webpage](https://bioc2022.bioconductor.org/workshops/).

**Comment by jdrnevich** [comment]
Hi Garth,

Orchestra and the website are two different things. You were supposed to have emailed ***@***.******@***.***> with the links to put on the website. We will work to put these in for all Orchestra workshops today.

Thanks,
Jenny

**Comment by seandavi** [comment]
@jmacdon Orchestra should point to your html now--just had to change the workshop URL to point to the HTML rather than github. I need to clarify the instructions. 

The HTML vignette doesn't end up in the docker, just the Rmd. I guess I could try to change that behavior if you think it would be useful to do so. I've been operating under the model that folks will go to the website for HTML.

**Comment by jmacdon** [comment]
@seandavi This is something I asked you about previously. I assume you are saying that orchestra is pointing to my githubio page, but that page doesn't have the vignettes. It's not like your page at all. https://jmacdon.github.io/Bioc2022Anno/

**Comment by seandavi** [comment]
I see what you are saying, @jmacdon. I see that the files in the gh-pages branch of your repo are correct for a pkgdown site. However, your site has only the README content on it. Could you double-check under Settings -> General -> Pages that the gh-pages branch is chosen as the source for Pages?

**Comment by jmacdon** [comment]
It is now. I must have missed that in the documentation! I assume I now just force the GitHub action to go again?

**Comment by jmacdon** [comment]
Ah, never mind. It builds automatically. Thanks @seandavi

**Comment by seandavi** [comment]
Glad we got it worked out. I think you have one of the longest-running workshops, so we have to make sure it goes by without a hitch! 😃
