### ISSUE TITLE
[New Workshop]: The Spectra Package

### ISSUE THREAD

**Issue by jorainer** [seandavi/orchestra-contributions#18]
Short title: The `Spectra` Package: a Flexible Infrastructure for Mass Spectrometry Data
Workshop URL: https://github.com/jorainer/SpectraTutorials/
Workshop docker image: https://hub.docker.com/r/jorainer/spectra_tutorials
Workshop port: 8787
Workshop memory request: 8GB
Workshop description:

Mass spectrometry (MS) data is a key technology in modern proteomics and metabolomics experiments. Due to continuous improvements in MS instrumentation, the generated data can easily become very large. Also, different additional resources of MS data exist, such as spectra libraries and databases, all with their own specific file formats that sometimes do not support manipulations of the original data.

Learning from experiences with the r Biocpkg("MSnbase") Bioconductor package we developed a novel infrastructure to handle MS spectral data in R, the r Biocpkg("Spectra") package. This package implements a clear separation of user functionality from code to provide, store and import mass spectrometry data. Different backends can hence be used to enable access to data from various data resources. Depending on the backend, data representations can be in memory, on disk, local or remote. Data manipulations are by default not directly applied to the data but cached in a lazy processing queue which allows analyses also of read-only data representations.

This workshop shows how this new infrastructure can be used to integrate data from a variety of different input sources on a simple example in which fragment (MS2) spectra from an experiment are matched against reference MS2 spectra from a public spectral library. Results are finally exported in a format commonly used for exchange of MS2 data.

Add any additional notes below.

**Comment by jorainer** [comment]
Hi Sean @seandavi - my workshop is still based on your older template - hope it's still OK.

**Comment by jorainer** [comment]
Actually - could be that this workshop is already in orchestra? I used it (in an older version) for EuroBioC2020 - this one (updated version) would be for EuroBioC2022.

**Comment by seandavi** [comment]
It is. Searching for `Spectra` pulls up the right workshop. I checked the version and it is definitely pulling the 2022 version now. Thanks for thinking of that detail. I think you are all set.

**Comment by jorainer** [comment]
Great, so I'm all set. Thanks Sean for your great resources!
