### ISSUE TITLE
benchdamic workshop

### ISSUE THREAD

**Issue by mcalgaro93** [seandavi/orchestra-contributions#19]
Please supply the following information:

Short title: The `benchdamic` package: benchmarking of differential abundance methods on microbiome data
Workshop URL: https://mcalgaro93.github.io/benchdamicWorkshop
Workshop docker image: ghcr.io/mcalgaro93/benchdamicworkshop
Workshop port: 8787
Workshop memory request: the image in my docker-desktop app weights a little more than 6GB
Workshop description: 
This workshop provides an introductory example on how to work with the analysis framework firstly proposed in the research article titled "Assessment of statistical methods from single cell, bulk RNA-seq, and metagenomics applied to microbiome data" by [Calgaro et al. (2020, Genome Biol)](https://doi.org/10.1186/s13059-020-02104-1) and now available in the `benchdamic` Bioconductor package. 
It is shown how to test commonly used methods for differential abundance (DA) analysis on a microbiome dataset and how to set up and benchmark custom methods. Performances of each method are evaluated with respect to i) suitability of distributional assumptions (GOF), ii) ability to control false positives (TIEC), iii) concordance of the findings, and iv) enrichment of DA microbial species in specific conditions.

**Comment by seandavi** [comment]
Sorry for the delay. This has been added. Thanks for the contribution....

**Comment by mcalgaro93** [comment]
Thank you Sean :)
