### ISSUE TITLE
[New Workshop]

### ISSUE THREAD

**Issue by ChristopherEeles** [seandavi/orchestra-contributions#2]
Please supply the following information:

Short title: Discovering Drug Synergy Biomarkers with PharmacoGx
Workshop URL: https://github.com/bhklab/bioc2022workshop
Workshop docker image: ghcr.io/bhklab/pgxBioc2022Workshop:latest
Workshop port: 8787
Workshop memory request: 4 GB
Workshop description: 
This workshop will introduce users to the CoreGx and PharmacoGx R
packages, which are useful tools for pharmacogenomic modelling to discover
biomarkers of treatment response in cancer model systems. PharmacoGx
specifically focuses on drug sensitivity experiments in cancer cell lines,
which will be the major focus of this workshop. Recent updates to PharmacoGx have
added support for analyzing drug combination experiments to discover molecular biomarkers
of drug synergy or antagonism. In this workshop users will learn how to use CoreGx and
PharmacoGx to build a PharmacoSet object from cancer cell-lines with both their molecular
phenotype and response to drug combination therapy characterized. This object will then be used
to compute common metrics of drug synergy and antagonism and to use available molecular
data to discover genes associated with response or resistance to both mono and drug combination
therapies.

**Comment by seandavi** [comment]
Thanks, @ChristopherEeles. I saw the issue with the build and agree that it looks like a problem on the sysreqs side. Let me know when you get things built and I'll add.

**Comment by seandavi** [comment]
Noted the issue in #5 and also saw that the issue with sysreqs should be fixed. Try rerunning the action.

**Comment by seandavi** [comment]
Looks good, @ChristopherEeles. Added and tested launch and everything seems in place.
