### ISSUE TITLE
[New Workshop] Bioconductor for HCA and CELLxGENE data discovery, exploration, and analysis

### ISSUE THREAD

**Issue by mtmorgan** [seandavi/orchestra-contributions#20]
Short title: Bioconductor for HCA and CELLxGENE data discovery, exploration, and analysis
Workshop URL: https://mtmorgan.github.io/HCABiocTraining
Workshop docker image: ghcr.io/mtmorgan/hcabioctraining:latest
Workshop port: 8787
Workshop memory request: 4GB
Workshop description: This workshop introduces R and Bioconductor for the discovery, analysis, and comprehension of single-cell genomic data. We start at the very beginning, with a brief introduction to R and its facilities for data analysis and visualization. We then move quickly to R and Bioconductor packages for discovery, retrieval, and input of single cell data, using examples from the CELLxGENE data portal. We take a quick look at existing, well-developed software for working with single-cell data, and conclude with a brief look at spatial and other emerging areas of research. The workshop should provide newcomers to R with enough knowledge to begin independent learning, while introducing more experienced users to the unique opportunities and challenges for single-cell analysis in R.

NOTE: building the workshop requires some python dependencies. The Dockerfile does this, but the `r-build-and-check` portion of the template workflow would require modification. As a pragmatic solution I  changes the container spec to 

```
    container: ghcr.io/mtmorgan/hcabioctraining:latest
```

This is a bit circular, but works once the container has settled down...

**Comment by seandavi** [comment]
Apologies, @mtmorgan, for the slow response. I just added and you should be all set.

**Comment by mtmorgan** [comment]
@seandavi this is so amazing!! (and I never give two '!' !). It blows my mind that I can click on the 'Launch' button on http://app.orchestra.cancerdatasci.org/1 and more-or-less instantly have exactly the more-or-less complicated R + Python + ... computational environment my trainees need. Wow.

**Comment by seandavi** [comment]
You made my day and even my week!
