### ISSUE TITLE
scRNAseq workshop 

### ISSUE THREAD

**Issue by aedin** [seandavi/orchestra-contributions#21]
Please supply the following information:

Short title: A short workflow with a basic scRNAseq workflow extracted and extended from the Unfiltered human PBMCs (10X Genomics) workflows in the "Orchestrating Single Cell Analysis with Bioconductor" book.
Workshop URL: , https://github.com/aedin/scRNAseqBasicWorkflow
Workshop docker image:  ghcr.io/aedin/scrnaseqbasicworkflow:latest
Workshop port: eg., 8787 for Rstudio-based workshops
Workshop memory request: eg., 2GB
Workshop description: a paragraph or two describing the workshop

Hi Sean 
We are doing a short scRNAseq course for students and wanted a simple workflow.  So we are extending the OSCA pbmc workflow. Can you put this on orchestra?

Add any additional notes below.

**Comment by seandavi** [comment]
You should be good-to-go. Thanks for adding this one!
