### ISSUE TITLE
Bioc2022Anno

### ISSUE THREAD

**Issue by jmacdon** [seandavi/orchestra-contributions#3]
Please supply the following information:

Short title: Introduction to Bioconductor annotation resources
Workshop URL: eg., https://github.com/jmacdon/Bioc2022Anno
Workshop docker image: eg., ghci.io/jmacdon/bioc2022anno
Workshop port: 8787 
Workshop memory request: 2GB
Workshop description: There are various annotation packages provided by the Bioconductor project that can be used to incorporate additional information to results from high-throughput experiments. This can be as simple as mapping Ensembl IDs to corresponding HUGO gene symbols, to much more complex queries involving multiple data sources. In this workshop we will cover the various classes of annotation packages, what they contain, and how to use them efficiently.

**Comment by seandavi** [comment]
Thanks, @jmacdon. You're all set. I added `2022` to the short title to distinguish from similar named workshops in the past.
