### ISSUE TITLE
Workshop builds but maybe not?

### ISSUE THREAD

**Issue by jmacdon** [seandavi/orchestra-contributions#4]
My workshop builds, and I do get a github.io page, but it's not like yours and the badge still says the build failed. I assume there's something going wrong, but I don't know how to track it down.

https://github.com/jmacdon/Bioc2022Anno
https://jmacdon.github.io/Bioc2022Anno/

**Comment by seandavi** [comment]
Seems like simply rerunning the actions should probably do the trick based on #5.

**Comment by seandavi** [comment]
Looks good now, @jmacdon. Added workshop and tested launch.
