### ISSUE TITLE
[New Workshop] MultiAssayWorkshop

### ISSUE THREAD

**Issue by LiNk-NY** [seandavi/orchestra-contributions#6]
Short title: Title: Multi-omic Integration and Analysis of cBioPortal and TCGA data with MultiAssayExperiment
Workshop URL: https://github.com/waldronlab/MultiAssayWorkshop
Workshop docker image: docker.io/mr148/multiassayworkshop:latest
Workshop port: 8787
Workshop memory request: 2GB
Workshop description: This is a workshop on acquiring and analyzing data through the
  curatedTCGAData and cBioPortalData packages as MultiAssayExperiment objects.
  It is built using GitHub actions and pkgdown. Some knowledge of R and basic 
  Bioconductor structures such as SummarizedExperiment is assumed.

**Comment by seandavi** [comment]
Hi, @LiNk-NY. Thanks for submitting. Your workshop is already loaded from 2020 and updates automatically with changes to the docker image. You're ready to go (just checked that the new version is what launches). If, in the future, you want to version this stuff, you can do that by versioning/tagging the docker image (and workshop materials).

**Comment by LiNk-NY** [comment]
Thanks Sean!
