### ISSUE TITLE
[New Workshop] Epidemiology for Bioinformaticians

### ISSUE THREAD

**Issue by cmirzayi** [seandavi/orchestra-contributions#7]
Please supply the following information:

Short title: Epidemiology for Bioinformaticians
Workshop URL: https://github.com/cmirzayi/epiforbioworkshop2022
Workshop docker image: eg., ghci.io/cmirzayi/epiforbioworkshop2022:latest
Workshop port: 8787
Workshop memory request: 2 GB
Workshop description:
Concepts of causal inference in epidemiology have important ramifications for studies across bioinformatics and other fields of health research. In this workshop, we introduce basic concepts of epidemiology, study design, and causal inference for bioinformaticians. Emphasis is placed on addressing bias and confounding as common threats to assessing a causal pathway in a variety of study design types and when using common forms of analyses such as GWAS and survival analysis. Workshop participants will have the opportunity to create their own structural causal models (DAGs) using dagitty and ggdag and then use this model to determine how to assess an estimated causal effect. Examples using DESeq2, edgeR, and limma will be used to show how multivariable models can be fitted depending on the hypothesized causal relationship.

**Comment by seandavi** [comment]
Thanks, @cmirzayi. The workshop has been added to Orchestra.
