### ISSUE TITLE
[New Workshop] Tidy Transcriptomics For Single-Cell RNA Sequencing Analyses

### ISSUE THREAD

**Issue by mblue9** [seandavi/orchestra-contributions#8]
Please supply the following information:

Short title: BioC2022: Tidy Transcriptomics For Single-Cell RNA Sequencing Analyses
_I've added BioC2022 in the short title as I think there are a few Tidy Transcriptomics workshops in Orchestra and some people last year were a little confused which to pick_
Workshop URL: https://github.com/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics
Workshop docker image: ghcr.io/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics
Workshop port: 8787
Workshop memory request: 2GB
Workshop description: 
This tutorial will present how to perform analysis of single-cell RNA sequencing data following the tidy data paradigm. The tidy data paradigm provides a standard way to organise data values within a dataset, where each variable is a column, each observation is a row, and data is manipulated using an easy-to-understand vocabulary. Most importantly, the data structure remains consistent across manipulation and analysis functions.

This can be achieved with the integration of packages present in the R CRAN and Bioconductor ecosystem, including [tidySingleCellExperiment](https://stemangiola.github.io/tidySingleCellExperiment/) and [tidyverse](https://www.tidyverse.org/). These packages are part of the tidytranscriptomics suite that introduces a tidy approach to RNA sequencing data representation and analysis. For more information see the [tidy transcriptomics blog](https://stemangiola.github.io/tidytranscriptomics/).

**Pre-requisites**
Basic familiarity with single-cell transcriptomic analyses
Basic familiarity with tidyverse

(ping @stemangiola)

**Comment by seandavi** [comment]
Hi, @mblue9. Could you double-check that the docker image exists and is publicly accessible? I'm getting an "unauthorized" when I try a `docker pull`.

**Comment by mblue9** [comment]
Ah @stemangiola can you make the image public as you have organization admin permission? Looks like you can do it under Package Settings on the right hand side of this page 
https://github.com/tidytranscriptomics-workshops/bioc2022_tidytranscriptomics/pkgs/container/bioc2022_tidytranscriptomics

**Comment by stemangiola** [comment]
Thanks @seandavi and @mblue9 ,

- I made the package public
- Enabled future public packages
- Made @mblue9 admin of the organisation

**Comment by seandavi** [comment]
Thanks, @mblue9 and @stemangiola. Your workshop has been added.

**Comment by mblue9** [comment]
Thanks @seandavi
