### ISSUE TITLE
SEESAW

### ISSUE THREAD

**Issue by mikelove** [seandavi/orchestra-contributions#9]
Please supply the following information:

Short title: SEESAW: Statistical Estimation Of Allelic Expression Using Salmon And Swish
Workshop URL: eg., https://github.com/mikelove/Bioc2022AllelicExpression/
Workshop docker image: eg., ghci.io/mikelove/Bioc2022AllelicExpression
Workshop port: eg., 8787 for Rstudio-based workshops
Workshop memory request: eg., 2GB
Workshop description: In this workshop, we will cover a newly developed suite of tools for performing analysis of allelic expression in Bioconductor. You will learn about how we use upstream tools like g2gtools and Salmon to quantify allelic expression for RNA-seq, and then how to explore the data in R using the fishpond package. Altogether we call this suite of tools SEESAW for "Statistical Estimation Of allelic Expression Using Salmon And sWish".

**Comment by seandavi** [comment]
Should be in. Thanks, @mikelove
